version: "3.8"

services:
  website:
    build: .
    ports:
      - "8080:80"
    volumes:
      # This line mounts your current folder into the container
      - ./:/usr/share/nginx/html/simon-game/
